name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The version to build. Must be a semver string.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - run: >
          cmake --preset msvc-configure
          -DAPP_REPO="${{ github.server_url }}/${{ github.repository }}"
          -DAPP_VERSION="${{ inputs.version }}"
          -DCMAKE_BUILD_TYPE="Release"
      - run: cmake --build --preset msvc-build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/*.exe
  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - run: gh release create ${{ inputs.version }} --latest --title ${{ inputs.version }} build/*
